import { useCallback, useEffect, useMemo, useState } from "react"
import { FlatList, Pressable, RefreshControl, StyleSheet, Text, TextInput, View } from "react-native"
import { useRouter } from "expo-router"
import { Search } from "lucide-react-native"
import { api } from "@/lib/api"
import type { Design, Product } from "@/types/api"
import { CatalogCard } from "@/components/CatalogCard"
import { EmptyState, ErrorState, LoadingState, PageHeader, Screen } from "@/components/ui"
import { useTheme } from "@/theme/theme"

export default function DesignsScreen() {
  const { colors } = useTheme(); const router = useRouter(); const [designs, setDesigns] = useState<Design[]>([]); const [products, setProducts] = useState<Product[]>([]); const [mode, setMode] = useState<"designs" | "products">("designs"); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState("")
  const load = useCallback(async () => { setError(""); try { const [looks, goods] = await Promise.all([api<Design[]>("/api/designs"), api<Product[]>("/api/products")]); setDesigns(looks); setProducts(goods) } catch (value) { setError((value as Error).message) } finally { setLoading(false); setRefreshing(false) } }, [])
  useEffect(() => { void load() }, [load])
  const visible = useMemo<(Design | Product)[]>(() => { const source = mode === "designs" ? designs : products; const needle = query.trim().toLowerCase(); return needle ? source.filter((item) => [item.title, item.garment_type || "", item.vendor_name || ""].some((value) => value.toLowerCase().includes(needle))) : source }, [designs, mode, products, query])
  return <Screen scroll={false}><PageHeader subtitle="Switch between made-to-measure designs and ready-to-buy clothing." title="Discover Vastrivo" /><View style={[styles.tabs, { backgroundColor: colors.surface, borderColor: colors.border }]}><Pressable onPress={() => setMode("designs")} style={[styles.tab, mode === "designs" && { backgroundColor: colors.primarySoft }]}><Text style={{ color: mode === "designs" ? colors.primary : colors.muted, fontFamily: "Manrope_700Bold" }}>Designs</Text></Pressable><Pressable onPress={() => setMode("products")} style={[styles.tab, mode === "products" && { backgroundColor: colors.primarySoft }]}><Text style={{ color: mode === "products" ? colors.primary : colors.muted, fontFamily: "Manrope_700Bold" }}>Shop</Text></Pressable></View><View style={[styles.search, { backgroundColor: colors.surface, borderColor: colors.border }]}><Search color={colors.muted} size={18} /><TextInput onChangeText={setQuery} placeholder={`Search ${mode}`} placeholderTextColor={colors.muted} style={{ color: colors.text, flex: 1, fontFamily: "Manrope_500Medium" }} value={query} /></View>{loading ? <LoadingState label="Loading collection…" /> : error ? <ErrorState message={error} retry={() => void load()} /> : <FlatList columnWrapperStyle={styles.row} contentContainerStyle={{ paddingBottom: 30 }} data={visible} key={`${mode}-grid`} keyExtractor={(item) => `${mode}-${item.id}`} ListEmptyComponent={<EmptyState message={`Approved vendor ${mode} will appear here.`} title={`No ${mode} found`} />} numColumns={2} refreshControl={<RefreshControl onRefresh={() => { setRefreshing(true); void load() }} refreshing={refreshing} tintColor={colors.primary} />} renderItem={({ item }) => mode === "designs" ? <CatalogCard eyebrow={`${item.category} · ${item.garment_type}`} imageUrls={item.images.map((image) => image.thumbnail_url || image.url)} onPress={() => router.push({ pathname: "/design/[id]", params: { id: String(item.id) } })} price={(item as Design).base_price} title={item.title} /> : <CatalogCard eyebrow={`${item.category} · ${(item as Product).unit}`} imageUrls={item.images.map((image) => image.thumbnail_url || image.url)} onPress={() => router.push({ pathname: "/product/[id]", params: { id: String(item.id) } })} price={(item as Product).price} title={item.title} />} />}</Screen>
}

const styles = StyleSheet.create({ tabs: { borderRadius: 14, borderWidth: 1, flexDirection: "row", marginBottom: 11, padding: 4 }, tab: { alignItems: "center", borderRadius: 11, flex: 1, padding: 10 }, search: { alignItems: "center", borderRadius: 14, borderWidth: 1, flexDirection: "row", gap: 9, marginBottom: 13, minHeight: 50, paddingHorizontal: 14 }, row: { marginHorizontal: -5 } })
