import * as ImagePicker from "expo-image-picker"
import { useEffect, useState } from "react"
import { Image, Pressable, StyleSheet, Text, View } from "react-native"
import { Camera, LogOut, Moon, UserRound } from "lucide-react-native"
import { useSession } from "@/auth/SessionProvider"
import { absoluteUrl, api, currentAccessToken } from "@/lib/api"
import type { UserProfile } from "@/types/api"
import { AppButton, Field, PageHeader, Pill, Screen } from "@/components/ui"
import { useTheme } from "@/theme/theme"

export default function ProfileScreen() {
  const { colors, toggleTheme } = useTheme(); const { profile, logout, reloadProfile } = useSession(); const [name, setName] = useState(profile?.full_name || ""); const [phone, setPhone] = useState(profile?.phone || ""); const [location, setLocation] = useState(profile?.location || ""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("")
  useEffect(() => { setName(profile?.full_name || ""); setPhone(profile?.phone || ""); setLocation(profile?.location || "") }, [profile])
  const save = async () => { setBusy(true); setError(""); setMessage(""); try { await api<UserProfile>("/api/auth/me", { method: "PUT", body: JSON.stringify({ full_name: name.trim(), phone: phone.trim() || null, location: location.trim() || null }) }); await reloadProfile(); setMessage("Profile updated") } catch (value) { setError((value as Error).message) } finally { setBusy(false) } }
  const choosePhoto = async () => { const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ["images"], allowsEditing: true, aspect: [1, 1], quality: 0.8 }); if (result.canceled) return; const asset = result.assets[0]; if (!asset.fileSize || asset.fileSize > 5 * 1024 * 1024 || !["image/jpeg", "image/png", "image/webp"].includes(asset.mimeType || "")) return setError("Choose a JPEG, PNG, or WebP profile photo up to 5 MB."); setBusy(true); setError(""); try { const data = new FormData(); data.append("file", { uri: asset.uri, name: asset.fileName || `profile-${Date.now()}.jpg`, type: asset.mimeType || "image/jpeg" } as unknown as Blob); await api<UserProfile>("/api/media/profile-image", { method: "POST", body: data }); await reloadProfile(); setMessage("Profile photo updated") } catch (value) { setError((value as Error).message) } finally { setBusy(false) } }
  const image = profile?.profile_image_url
  return <Screen><PageHeader action={<Pill tone="primary">{profile?.role.replaceAll("_", " ")}</Pill>} subtitle="Your account identity and mobile preferences." title="Profile & settings" /><View style={[styles.identity, { backgroundColor: colors.surface, borderColor: colors.border }]}><Pressable accessibilityLabel="Change profile photo" disabled={busy} onPress={() => void choosePhoto()} style={[styles.avatar, { backgroundColor: colors.primarySoft }]}>{image ? <Image source={{ uri: absoluteUrl(image), headers: currentAccessToken() ? { Authorization: `Bearer ${currentAccessToken()}` } : undefined }} style={styles.avatarImage} /> : <UserRound color={colors.primary} size={32} />}<View style={[styles.camera, { backgroundColor: colors.primary }]}><Camera color={colors.white} size={13} /></View></Pressable><View style={{ flex: 1 }}><Text style={{ color: colors.text, fontFamily: "Fraunces_700Bold", fontSize: 22 }}>{profile?.full_name}</Text><Text style={{ color: colors.muted, fontFamily: "Manrope_400Regular", marginTop: 3 }}>{profile?.email}</Text><Text style={{ color: colors.primary, fontFamily: "Manrope_700Bold", fontSize: 12, marginTop: 7 }}>Tap photo to update</Text></View></View><Field label="Full name" maxLength={100} onChangeText={setName} value={name} /><Field keyboardType="phone-pad" label="Phone number" maxLength={20} onChangeText={setPhone} value={phone} /><Field label="Location" maxLength={150} onChangeText={setLocation} placeholder="City, State" value={location} />{!!error && <Text style={{ color: colors.danger, marginBottom: 12 }}>{error}</Text>}{!!message && <Text style={{ color: colors.success, fontFamily: "Manrope_600SemiBold", marginBottom: 12 }}>{message}</Text>}<AppButton disabled={busy || name.trim().length < 2} onPress={() => void save()}>{busy ? "Saving…" : "Save changes"}</AppButton><View style={{ height: 12 }} /><AppButton onPress={toggleTheme} variant="secondary"><Moon size={16} /> Change theme</AppButton><View style={{ height: 12 }} /><AppButton onPress={() => void logout()} variant="danger"><LogOut size={16} /> Sign out</AppButton></Screen>
}

const styles = StyleSheet.create({ identity: { alignItems: "center", borderRadius: 19, borderWidth: 1, flexDirection: "row", gap: 13, marginBottom: 22, padding: 15 }, avatar: { alignItems: "center", borderRadius: 18, height: 66, justifyContent: "center", width: 66 }, avatarImage: { borderRadius: 18, height: "100%", width: "100%" }, camera: { alignItems: "center", borderRadius: 99, bottom: -4, height: 24, justifyContent: "center", position: "absolute", right: -4, width: 24 } })
