import { useCallback, useEffect, useMemo, useState } from "react"
import { FlatList, Image, Pressable, RefreshControl, StyleSheet, Text, TextInput, View } from "react-native"
import { useRouter } from "expo-router"
import { Heart, MapPin, Search, Store } from "lucide-react-native"
import { absoluteUrl, api, currentAccessToken } from "@/lib/api"
import type { VendorDirectoryItem } from "@/types/api"
import { EmptyState, ErrorState, LoadingState, PageHeader, Screen } from "@/components/ui"
import { useTheme } from "@/theme/theme"

export default function VendorsScreen() {
  const { colors } = useTheme(); const router = useRouter(); const [items, setItems] = useState<VendorDirectoryItem[]>([]); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState("")
  const load = useCallback(async () => { setError(""); try { setItems(await api<VendorDirectoryItem[]>("/api/vendors")) } catch (value) { setError((value as Error).message) } finally { setLoading(false); setRefreshing(false) } }, [])
  useEffect(() => { void load() }, [load])
  const visible = useMemo(() => { const needle = query.trim().toLowerCase(); return needle ? items.filter((item) => [item.shop_name, item.full_name, item.location || ""].some((value) => value.toLowerCase().includes(needle))) : items }, [items, query])
  const favorite = async (vendor: VendorDirectoryItem) => { const next = !vendor.is_favorite; setItems((current) => current.map((item) => item.id === vendor.id ? { ...item, is_favorite: next } : item)); try { await api(`/api/vendors/${vendor.id}/favorite`, { method: next ? "POST" : "DELETE" }) } catch { setItems((current) => current.map((item) => item.id === vendor.id ? { ...item, is_favorite: !next } : item)) } }
  return <Screen scroll={false}><PageHeader subtitle="Browse verified shops, save favorites, and discuss custom work." title="Tailoring partners" /><View style={[styles.search, { backgroundColor: colors.surface, borderColor: colors.border }]}><Search color={colors.muted} size={18} /><TextInput onChangeText={setQuery} placeholder="Shop, tailor, or location" placeholderTextColor={colors.muted} style={{ color: colors.text, flex: 1, fontFamily: "Manrope_500Medium" }} value={query} /></View>{loading ? <LoadingState label="Loading vendors…" /> : error ? <ErrorState message={error} retry={() => void load()} /> : <FlatList contentContainerStyle={{ gap: 12, paddingBottom: 30 }} data={visible} keyExtractor={(item) => String(item.id)} ListEmptyComponent={<EmptyState message="Try a different shop, tailor, or location." title="No vendors found" />} refreshControl={<RefreshControl onRefresh={() => { setRefreshing(true); void load() }} refreshing={refreshing} tintColor={colors.primary} />} renderItem={({ item }) => <Pressable onPress={() => router.push({ pathname: "/vendor/[id]", params: { id: String(item.id) } })} style={({ pressed }) => [styles.card, { backgroundColor: colors.surface, borderColor: colors.border, opacity: pressed ? 0.8 : 1 }]}><View style={[styles.logo, { backgroundColor: colors.primarySoft }]}>{item.logo_url ? <Image source={{ uri: absoluteUrl(item.logo_url), headers: currentAccessToken() ? { Authorization: `Bearer ${currentAccessToken()}` } : undefined }} style={styles.logoImage} /> : <Store color={colors.primary} size={27} />}</View><View style={{ flex: 1 }}><Text style={{ color: colors.primary, fontFamily: "Manrope_700Bold", fontSize: 10, textTransform: "uppercase" }}>{item.full_name}</Text><Text style={{ color: colors.text, fontFamily: "Fraunces_700Bold", fontSize: 21, marginTop: 2 }}>{item.shop_name}</Text>{item.location && <Text numberOfLines={1} style={{ color: colors.muted, fontFamily: "Manrope_400Regular", fontSize: 12, marginTop: 7 }}><MapPin color={colors.muted} size={12} /> {item.location}</Text>}</View><Pressable accessibilityLabel={`${item.is_favorite ? "Remove" : "Add"} favorite vendor`} hitSlop={10} onPress={(event) => { event.stopPropagation(); void favorite(item) }}><Heart color={item.is_favorite ? colors.primary : colors.muted} fill={item.is_favorite ? colors.primary : "none"} size={22} /></Pressable></Pressable>} />}</Screen>
}

const styles = StyleSheet.create({ search: { alignItems: "center", borderRadius: 14, borderWidth: 1, flexDirection: "row", gap: 9, marginBottom: 14, minHeight: 50, paddingHorizontal: 14 }, card: { alignItems: "center", borderRadius: 18, borderWidth: 1, flexDirection: "row", gap: 13, padding: 14 }, logo: { alignItems: "center", borderRadius: 15, height: 58, justifyContent: "center", overflow: "hidden", width: 58 }, logoImage: { height: "100%", width: "100%" } })
