import * as Location from "expo-location"
import { useCallback, useEffect, useState } from "react"
import { FlatList, Linking, Pressable, RefreshControl, StyleSheet, Text, View } from "react-native"
import { MapPin, Navigation, PackageCheck, Scissors, Store } from "lucide-react-native"
import { useRouter } from "expo-router"
import { useSession } from "@/auth/SessionProvider"
import { api } from "@/lib/api"
import type { DeliveryJob, Order, PaginatedDeliveries, PaginatedOrders, UserProfile, VendorSummary } from "@/types/api"
import { AppButton, EmptyState, ErrorState, Field, Heading, LoadingState, PageHeader, Pill, Screen } from "@/components/ui"
import { useTheme } from "@/theme/theme"

const CustomerWorkspace = () => {
  const { colors } = useTheme(); const { profile, reloadProfile } = useSession(); const [shopName, setShopName] = useState(profile?.vendor_request_shop_name || ""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("")
  if (profile?.vendor_request_status === "pending") return <View style={[styles.panel, { backgroundColor: colors.surface, borderColor: colors.border }]}><Store color={colors.primary} size={30} /><Heading size={23}>Vendor request under review</Heading><Text style={{ color: colors.muted, fontFamily: "Manrope_400Regular", lineHeight: 21 }}>Administrators will review your shop information. You will receive an activity update after a decision.</Text></View>
  const submit = async () => { setBusy(true); setError(""); try { await api<UserProfile>("/api/vendors/request", { method: "POST", body: JSON.stringify({ shop_name: shopName.trim(), message: message.trim() || null }) }); await reloadProfile() } catch (value) { setError((value as Error).message) } finally { setBusy(false) } }
  return <View><View style={[styles.panel, { backgroundColor: colors.surface, borderColor: colors.border }]}><Store color={colors.primary} size={30} /><Heading size={23}>{profile?.vendor_request_status === "rejected" ? "Update your vendor request" : "Become a Vastrivo vendor"}</Heading><Text style={{ color: colors.muted, fontFamily: "Manrope_400Regular", lineHeight: 21 }}>Tell us about your tailoring shop. Vendor access is enabled only after administrator review.</Text>{profile?.vendor_request_status === "rejected" && <Text style={{ color: colors.danger, fontFamily: "Manrope_600SemiBold" }}>Previous request was not approved. Update the details and submit again.</Text>}</View><Field label="Shop name" maxLength={150} onChangeText={setShopName} value={shopName} /><Field label="About your tailoring work (optional)" maxLength={2000} multiline numberOfLines={5} onChangeText={setMessage} style={{ minHeight: 110, textAlignVertical: "top" }} value={message} />{!!error && <Text style={{ color: colors.danger, marginBottom: 12 }}>{error}</Text>}<AppButton disabled={busy || shopName.trim().length < 2} onPress={submit}>{busy ? "Submitting…" : "Submit vendor request"}</AppButton></View>
}

const VendorWorkspace = () => {
  const { colors } = useTheme(); const router = useRouter(); const [summary, setSummary] = useState<VendorSummary | null>(null); const [orders, setOrders] = useState<Order[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("")
  const load = useCallback(async () => { setError(""); try { const [counts, sales] = await Promise.all([api<VendorSummary>("/api/vendor/summary"), api<PaginatedOrders>("/api/orders/vendor?limit=10&offset=0")]); setSummary(counts); setOrders(sales.items) } catch (value) { setError((value as Error).message) } finally { setLoading(false) } }, [])
  useEffect(() => { void load() }, [load])
  if (loading) return <LoadingState label="Opening your studio…" />
  if (error) return <ErrorState message={error} retry={() => void load()} />
  return <View><AppButton onPress={() => router.push("/studio/designs")}>Manage designs & photos</AppButton><View style={[styles.metrics, { marginTop: 16 }]}>{(["draft", "submitted", "approved", "rejected"] as const).map((key) => <View key={key} style={[styles.metric, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={{ color: colors.text, fontFamily: "Fraunces_700Bold", fontSize: 25 }}>{summary?.[key] || 0}</Text><Text style={{ color: colors.muted, fontFamily: "Manrope_600SemiBold", fontSize: 11, textTransform: "capitalize" }}>{key}</Text></View>)}</View><Text style={{ color: colors.text, fontFamily: "Fraunces_700Bold", fontSize: 24, marginBottom: 12, marginTop: 18 }}>Recent customer orders</Text>{orders.length ? orders.map((order) => <Pressable key={order.id} onPress={() => router.push(`/order/${order.id}`)} style={[styles.orderRow, { backgroundColor: colors.surface, borderColor: colors.border }]}><Scissors color={colors.primary} size={21} /><View style={{ flex: 1 }}><Text style={{ color: colors.text, fontFamily: "Manrope_700Bold" }}>Order #{order.id}</Text><Text style={{ color: colors.muted, fontFamily: "Manrope_400Regular", fontSize: 12 }}>{order.order_items.length} tailoring item{order.order_items.length === 1 ? "" : "s"}</Text></View><Pill tone="primary">{order.status.replaceAll("_", " ")}</Pill></Pressable>) : <EmptyState message="Orders placed with your shop will appear here." title="No sales orders" />}</View>
}

const DeliveryWorkspace = () => {
  const { colors } = useTheme(); const [jobs, setJobs] = useState<DeliveryJob[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState("")
  const load = useCallback(async () => { setError(""); try { setJobs((await api<PaginatedDeliveries>("/api/delivery-agent/deliveries?limit=30&offset=0")).items) } catch (value) { setError((value as Error).message) } finally { setLoading(false); setRefreshing(false) } }, [])
  useEffect(() => { void load() }, [load])
  const shareLocation = async () => { const permission = await Location.requestForegroundPermissionsAsync(); if (permission.status !== "granted") return setError("Location permission is required only when you choose to share your position."); const position = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.High }); await api("/api/delivery-agent/location", { method: "PUT", body: JSON.stringify({ latitude: position.coords.latitude, longitude: position.coords.longitude, accuracy_meters: position.coords.accuracy }) }); await load() }
  const updateStatus = async (job: DeliveryJob) => { const next = job.status === "booked" ? "picked_up" : job.status === "picked_up" ? "in_transit" : job.status === "in_transit" ? "delivered" : null; if (!next) return; await api(`/api/delivery-agent/deliveries/${job.id}/status`, { method: "PATCH", body: JSON.stringify({ status: next }) }); await load() }
  if (loading) return <LoadingState label="Loading assigned deliveries…" />
  if (error && !jobs.length) return <ErrorState message={error} retry={() => void load()} />
  return <View style={{ flex: 1 }}><AppButton onPress={() => void shareLocation()} variant="secondary">Share my current location</AppButton>{!!error && <Text style={{ color: colors.danger, marginTop: 10 }}>{error}</Text>}<FlatList contentContainerStyle={{ gap: 12, paddingBottom: 30, paddingTop: 16 }} data={jobs} keyExtractor={(item) => String(item.id)} ListEmptyComponent={<EmptyState message="Administrators will assign booked deliveries here." title="No assigned deliveries" />} refreshControl={<RefreshControl onRefresh={() => { setRefreshing(true); void load() }} refreshing={refreshing} tintColor={colors.primary} />} renderItem={({ item }) => <View style={[styles.deliveryCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.deliveryTitle}><PackageCheck color={colors.primary} size={22} /><Text style={{ color: colors.text, flex: 1, fontFamily: "Fraunces_700Bold", fontSize: 19 }}>Delivery #{item.id}</Text><Pill tone={item.status === "delivered" ? "success" : "primary"}>{item.status.replaceAll("_", " ")}</Pill></View><Text style={[styles.routeLabel, { color: colors.muted }]}>PICKUP · {item.vendor_name}</Text><Text style={[styles.address, { color: colors.text }]}>{item.origin_address}</Text><Text style={[styles.routeLabel, { color: colors.muted }]}>DELIVER TO · {item.customer_name}</Text><Text style={[styles.address, { color: colors.text }]}>{item.destination_address}</Text><View style={styles.deliveryActions}><Pressable onPress={() => void Linking.openURL(`https://www.google.com/maps/dir/?api=1&origin=${item.origin_latitude},${item.origin_longitude}&destination=${item.destination_latitude},${item.destination_longitude}`)} style={[styles.mapButton, { borderColor: colors.border }]}><Navigation color={colors.text} size={17} /><Text style={{ color: colors.text, fontFamily: "Manrope_700Bold" }}>Route</Text></Pressable>{!["delivered", "cancelled"].includes(item.status) && <View style={{ flex: 1 }}><AppButton onPress={() => void updateStatus(item)}>{item.status === "booked" ? "Confirm pickup" : item.status === "picked_up" ? "Start delivery" : "Mark delivered"}</AppButton></View>}</View></View>} /></View>
}

export default function WorkspaceScreen() {
  const { profile } = useSession()
  const title = profile?.role === "vendor" ? "Vendor studio" : profile?.role === "delivery_agent" ? "Delivery partner" : profile?.role === "customer" ? "Your workspace" : "Administration"
  const subtitle = profile?.role === "vendor" ? "Manage shop work and customer orders." : profile?.role === "delivery_agent" ? "Assigned pickups and deliveries." : "Role-specific tools and applications."
  return <Screen scroll={profile?.role !== "delivery_agent"}><PageHeader subtitle={subtitle} title={title} />{profile?.role === "customer" ? <CustomerWorkspace /> : profile?.role === "vendor" ? <VendorWorkspace /> : profile?.role === "delivery_agent" ? <DeliveryWorkspace /> : <EmptyState message="Use the Vastrivo web administration workspace for moderation, users, payments, settlements, and delivery dispatch." title="Administration is web-first" />}</Screen>
}

const styles = StyleSheet.create({ panel: { borderRadius: 20, borderWidth: 1, gap: 10, marginBottom: 20, padding: 19 }, metrics: { flexDirection: "row", flexWrap: "wrap", gap: 9 }, metric: { borderRadius: 16, borderWidth: 1, minWidth: "47%", padding: 14 }, orderRow: { alignItems: "center", borderRadius: 15, borderWidth: 1, flexDirection: "row", gap: 11, marginBottom: 9, padding: 13 }, note: { borderRadius: 15, marginTop: 18, padding: 15 }, deliveryCard: { borderRadius: 18, borderWidth: 1, padding: 15 }, deliveryTitle: { alignItems: "center", flexDirection: "row", gap: 9, marginBottom: 15 }, routeLabel: { fontFamily: "Manrope_700Bold", fontSize: 10, marginTop: 8 }, address: { fontFamily: "Manrope_500Medium", lineHeight: 20, marginTop: 4 }, deliveryActions: { alignItems: "center", flexDirection: "row", gap: 9, marginTop: 16 }, mapButton: { alignItems: "center", borderRadius: 14, borderWidth: 1, flexDirection: "row", gap: 7, minHeight: 50, paddingHorizontal: 15 } })
