import { useCallback, useEffect, useMemo, useRef, useState } from "react"
import * as ImagePicker from "expo-image-picker"
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native"
import { useFocusEffect, useLocalSearchParams } from "expo-router"
import { CircleCheckBig, CreditCard, FilePenLine, MessageSquareText, PackageCheck, Scissors, Send } from "lucide-react-native"
import { useSession } from "@/auth/SessionProvider"
import { api } from "@/lib/api"
import type { InvoiceSummary, Order, OrderComment, OrderItem } from "@/types/api"
import { openRazorpayCheckout, type PaymentScope } from "@/payments/razorpay"
import { OrderInvoiceEditor } from "@/components/OrderInvoiceEditor"
import { AppButton, ErrorState, Field, LoadingState, PageHeader, Pill, Screen } from "@/components/ui"
import { useTheme } from "@/theme/theme"

const workLabels: Record<string, string> = { awaiting_invoice: "Awaiting invoice", awaiting_approval: "Awaiting approval", awaiting_cloth_payment: "Awaiting cloth payment", awaiting_payment_verification: "Verifying payment", awaiting_cloth: "Awaiting customer cloth", ready_to_start: "Ready to start", fabric_cutting: "Fabric cutting", stitching: "Stitching", quality_check: "Quality check", completed: "Completed" }
const nextWorkLabel: Record<string, string> = { ready_to_start: "Start tailoring", fabric_cutting: "Move to stitching", stitching: "Move to quality check", quality_check: "Mark completed" }

type WorkflowStageKey = "invoice" | "tailoring" | "payment" | "fulfilment"
type WorkflowStageState = "complete" | "current" | "pending"
type WorkflowStage = { detail: string; key: WorkflowStageKey; label: string; state: WorkflowStageState }

const workRank: Record<string, number> = { awaiting_invoice: 0, awaiting_approval: 0, awaiting_cloth_payment: 0, awaiting_payment_verification: 0, awaiting_cloth: 0, ready_to_start: 1, fabric_cutting: 2, stitching: 3, quality_check: 4, completed: 5 }

const buildWorkflowStages = (order: Order): WorkflowStage[] => {
  const activeItems = order.order_items.filter((item) => !["cancelled", "rejected"].includes(item.work_status))
  const invoices = (order.combined_order ? [order.invoice] : activeItems.map((item) => item.invoice)).filter((invoice): invoice is InvoiceSummary => Boolean(invoice))
  const expectedInvoices = order.combined_order ? 1 : activeItems.length
  const invoiceComplete = expectedInvoices > 0 && invoices.length === expectedInvoices && invoices.every((invoice) => invoice.status === "approved")
  const allTailoringComplete = activeItems.length > 0 && activeItems.every((item) => item.work_status === "completed")
  const completedItems = activeItems.filter((item) => item.work_status === "completed").length
  const leastAdvancedItem = [...activeItems].sort((left, right) => (workRank[left.work_status] ?? 0) - (workRank[right.work_status] ?? 0))[0]
  const invoiceDetail = invoiceComplete
    ? "Approved"
    : invoices.some((invoice) => invoice.status === "change_requested")
      ? "Changes requested"
      : invoices.some((invoice) => invoice.status === "issued")
        ? "Awaiting approval"
        : invoices.length
          ? "Draft"
          : "Not prepared"
  const tailoringDetail = allTailoringComplete
    ? "Completed"
    : activeItems.length > 1 && completedItems > 0
      ? `${completedItems}/${activeItems.length} complete · ${workLabels[leastAdvancedItem?.work_status] || "In progress"}`
      : workLabels[leastAdvancedItem?.work_status] || "Not started"
  const finalPaid = invoices.length > 0 && invoices.every((invoice) => invoice.final_payment_status === "paid")
  const delivery = order.deliveries[0]
  const fulfilmentStarted = ["ready_for_shipping", "shipped", "delivered"].includes(order.status) || Boolean(delivery && !["quoted", "pending", "booked"].includes(delivery.status))
  const fulfilmentDetail = order.status === "delivered" || delivery?.status === "delivered"
    ? "Delivered"
    : delivery?.status === "in_transit"
      ? "In transit"
      : delivery?.status === "picked_up"
        ? "Picked up"
        : order.status === "ready_for_shipping" || delivery?.status === "booked"
          ? "Ready for pickup"
          : finalPaid
            ? "Waiting for vendor"
            : "After payment"

  return [
    { detail: invoiceDetail, key: "invoice", label: "Invoice", state: invoiceComplete ? "complete" : "current" },
    { detail: tailoringDetail, key: "tailoring", label: "Tailoring", state: allTailoringComplete ? "complete" : invoiceComplete ? "current" : "pending" },
    { detail: finalPaid ? "Paid" : allTailoringComplete ? "Payment due" : "After tailoring", key: "payment", label: "Payment", state: finalPaid ? "complete" : allTailoringComplete ? "current" : "pending" },
    { detail: fulfilmentDetail, key: "fulfilment", label: order.status === "delivered" ? "Delivered" : "Fulfilment", state: order.status === "delivered" || delivery?.status === "delivered" ? "complete" : finalPaid || fulfilmentStarted ? "current" : "pending" },
  ]
}

const OrderChat = ({ item }: { item: OrderItem }) => {
  const { colors } = useTheme(); const { profile } = useSession(); const [comments, setComments] = useState<OrderComment[]>(item.comments || []); const [message, setMessage] = useState(""); const [sending, setSending] = useState(false); const [error, setError] = useState(""); const latest = useRef(Math.max(0, ...(item.comments || []).map((entry) => entry.id)))
  useEffect(() => { setComments(item.comments || []); latest.current = Math.max(0, ...(item.comments || []).map((entry) => entry.id)) }, [item.comments])
  useEffect(() => { let active = true; const poll = async () => { try { const updates = await api<OrderComment[]>(`/api/orders/items/${item.id}/comments?after_id=${latest.current}`); if (!active || !updates.length) return; setComments((current) => { const merged = new Map(current.map((entry) => [entry.id, entry])); updates.forEach((entry) => merged.set(entry.id, entry)); return [...merged.values()].sort((a, b) => a.id - b.id) }); latest.current = Math.max(latest.current, ...updates.map((entry) => entry.id)) } catch { /* Retry on the next lightweight poll. */ } }; const timer = setInterval(() => void poll(), 5000); return () => { active = false; clearInterval(timer) } }, [item.id])
  const send = async () => { const value = message.trim(); if (!value) return; setSending(true); setError(""); try { const updated = await api<OrderItem>(`/api/orders/items/${item.id}/comments`, { method: "POST", body: JSON.stringify({ message: value }) }); setComments(updated.comments); latest.current = Math.max(0, ...updated.comments.map((entry) => entry.id)); setMessage("") } catch (reason) { setError((reason as Error).message) } finally { setSending(false) } }
  return <View style={[styles.chat, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.chatHeading}><MessageSquareText color={colors.primary} size={20} /><View><Text style={{ color: colors.text, fontFamily: "Manrope_700Bold" }}>Order chat</Text><Text style={{ color: colors.muted, fontFamily: "Manrope_400Regular", fontSize: 11 }}>Customer and vendor messages for this item.</Text></View></View><View style={styles.messages}>{comments.length ? comments.map((entry) => <View key={entry.id} style={[styles.message, entry.author_id === profile?.id ? { alignSelf: "flex-end", backgroundColor: colors.primarySoft, borderColor: colors.primary } : { alignSelf: "flex-start", backgroundColor: colors.surfaceMuted, borderColor: colors.border }]}><Text style={{ color: colors.text, fontFamily: "Manrope_700Bold", fontSize: 12 }}>{entry.author_name}</Text><Text style={{ color: colors.text, fontFamily: "Manrope_400Regular", fontSize: 14, lineHeight: 20, marginTop: 3 }}>{entry.message}</Text><Text style={{ color: colors.muted, fontFamily: "Manrope_500Medium", fontSize: 9, marginTop: 5 }}>{entry.author_role.replaceAll("_", " ")} · {new Date(entry.created_at).toLocaleString("en-IN", { day: "numeric", month: "short", hour: "numeric", minute: "2-digit" })}</Text></View>) : <Text style={{ color: colors.muted, fontFamily: "Manrope_400Regular", paddingVertical: 13, textAlign: "center" }}>No messages yet. Start the order conversation here.</Text>}</View>{!!error && <Text style={{ color: colors.danger, fontFamily: "Manrope_600SemiBold", fontSize: 12, marginBottom: 8 }}>{error}</Text>}<View style={styles.composer}><TextInput maxLength={2000} multiline onChangeText={setMessage} placeholder="Write a message…" placeholderTextColor={colors.muted} style={[styles.chatInput, { backgroundColor: colors.surfaceMuted, borderColor: colors.border, color: colors.text }]} value={message} /><Pressable accessibilityLabel="Send message" disabled={sending || !message.trim()} onPress={() => void send()} style={[styles.sendButton, { backgroundColor: colors.primary, opacity: sending || !message.trim() ? 0.45 : 1 }]}><Send color={colors.white} size={18} /></Pressable></View></View>
}

const InvoiceCard = ({ invoice, colors }: { invoice: InvoiceSummary; colors: ReturnType<typeof useTheme>["colors"] }) => <View style={[styles.invoice, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.invoiceHeader}><View><Text style={{ color: colors.primary, fontFamily: "Manrope_700Bold", fontSize: 10 }}>VENDOR INVOICE</Text><Text style={{ color: colors.text, fontFamily: "Fraunces_700Bold", fontSize: 20 }}>{invoice.invoice_number}</Text></View><Pill tone={invoice.status === "approved" ? "success" : "primary"}>{invoice.status.replaceAll("_", " ")}</Pill></View><Text style={{ color: colors.muted, fontFamily: "Manrope_400Regular", lineHeight: 19 }}>{invoice.cloth_type}</Text><Text style={{ color: colors.text, fontFamily: "Manrope_600SemiBold", lineHeight: 20, marginTop: 4 }}>{invoice.cloth_requirement}</Text><View style={styles.invoiceTotals}><Text style={{ color: colors.muted, fontFamily: "Manrope_600SemiBold" }}>Tailoring ₹{invoice.service_amount.toLocaleString("en-IN")} · Cloth ₹{invoice.cloth_cost.toLocaleString("en-IN")} · Extras ₹{invoice.additional_amount.toLocaleString("en-IN")}</Text><Text style={{ color: colors.primary, fontFamily: "Fraunces_700Bold", fontSize: 24 }}>₹{invoice.total_amount.toLocaleString("en-IN")}</Text></View></View>

export default function OrderDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { colors } = useTheme(); const { profile } = useSession(); const [order, setOrder] = useState<Order | null>(null); const [loading, setLoading] = useState(true); const [paying, setPaying] = useState(false); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [decisionNote, setDecisionNote] = useState(""); const [invoiceTarget, setInvoiceTarget] = useState<OrderItem | "combined" | null>(null)
  const load = useCallback(async (quiet = false) => { if (!quiet) setError(""); try { setOrder(await api<Order>(`/api/orders/${id}`)) } catch (value) { if (!quiet) setError((value as Error).message) } finally { if (!quiet) setLoading(false) } }, [id])
  useFocusEffect(useCallback(() => { void load(); const timer = setInterval(() => void load(true), 5000); return () => clearInterval(timer) }, [load]))
  const isVendor = profile?.role === "vendor"; const isCustomer = Boolean(order && profile?.id === order.customer.id)
  const payment = useMemo(() => { if (!order) return null; const combined = order.combined_order && order.invoice ? { invoice: order.invoice, resourceId: order.id, prefix: "combined_order" as const } : order.order_items.length === 1 && order.order_items[0].invoice ? { invoice: order.order_items[0].invoice, resourceId: order.order_items[0].id, prefix: "order_item" as const } : null; if (!combined || combined.invoice.status !== "approved") return null; if (combined.invoice.payment_status === "pending" && combined.invoice.cloth_cost > 0 && combined.invoice.cloth_bill_url) return { label: `Pay cloth cost · ₹${combined.invoice.cloth_cost.toLocaleString("en-IN")}`, scope: combined.prefix as PaymentScope, resourceId: combined.resourceId }; const complete = order.order_items.every((item) => item.work_status === "completed"); if (complete && combined.invoice.final_payment_status === "pending") return { label: "Pay final order balance", scope: `${combined.prefix}_final` as PaymentScope, resourceId: combined.resourceId }; return null }, [order])
  const pay = async () => { if (!payment) return; setPaying(true); try { const result = await openRazorpayCheckout(payment.scope, payment.resourceId); Alert.alert("Payment verified", result.message); await load() } catch (value) { const failure = value as { description?: string; message?: string }; Alert.alert("Payment not completed", failure.description || failure.message || "You can safely try again.") } finally { setPaying(false) } }
  const action = async (path: string, method = "POST", body?: object) => { setBusy(path); setError(""); try { await api(path, { method, body: body ? JSON.stringify(body) : undefined }); await load(); return true } catch (value) { setError((value as Error).message); return false } finally { setBusy("") } }
  const decide = async (item: OrderItem | undefined, decision: "approved" | "change_requested" = "approved") => { if (decision === "change_requested" && decisionNote.trim().length < 2) return setError("Add a note explaining the requested invoice change."); const path = order!.combined_order && !item ? `/api/orders/${order!.id}/invoice/decision` : `/api/orders/items/${item!.id}/invoice/decision`; if (await action(path, "POST", { decision, comment: decisionNote.trim() || null })) setDecisionNote("") }
  const vendorProgress = async (item: OrderItem) => { if (!order) return; const path = order.combined_order ? `/api/orders/vendor/${order.id}/items/${item.id}/advance` : item.work_status === "ready_to_start" ? `/api/orders/vendor/items/${item.id}/start` : `/api/orders/vendor/items/${item.id}/advance`; await action(path) }
  const attachClothBill = async (item?: OrderItem) => {
    const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ["images"], quality: 0.9 })
    if (result.canceled) return
    const asset = result.assets[0]
    if (!asset.fileSize || asset.fileSize > 5 * 1024 * 1024 || !["image/jpeg", "image/png", "image/webp"].includes(asset.mimeType || "")) return setError("Choose a JPEG, PNG, or WebP cloth bill up to 5 MB.")
    setBusy("cloth-bill"); setError("")
    try {
      const data = new FormData()
      data.append("file", { uri: asset.uri, name: asset.fileName || `cloth-bill-${Date.now()}.jpg`, type: asset.mimeType || "image/jpeg" } as unknown as Blob)
      const path = order!.combined_order && !item ? `/api/orders/vendor/${order!.id}/invoice/cloth-bill` : `/api/orders/vendor/items/${item!.id}/invoice/cloth-bill`
      await api(path, { method: "POST", body: data }); await load()
    } catch (value) { setError((value as Error).message) }
    finally { setBusy("") }
  }
  if (loading) return <Screen scroll={false}><LoadingState label="Opening order…" /></Screen>
  if (error && !order) return <Screen><PageHeader back title="Order" /><ErrorState message={error || "Order not found"} retry={() => void load()} /></Screen>
  if (!order) return null
  const combinedInvoice = order.combined_order ? order.invoice : null; const canEditCombined = isVendor && order.combined_order && (!combinedInvoice || ["draft", "change_requested"].includes(combinedInvoice.status)); const allComplete = order.order_items.length > 0 && order.order_items.every((item) => ["completed", "cancelled", "rejected"].includes(item.work_status)); const workflowStages = buildWorkflowStages(order)
  return <Screen><PageHeader action={<Pill tone={order.status === "delivered" ? "success" : "primary"}>{order.status.replaceAll("_", " ")}</Pill>} back subtitle={`Placed ${new Date(order.created_at).toLocaleString("en-IN")}`} title={`Order #${order.id}`} /><View style={[styles.summary, { backgroundColor: colors.surface, borderColor: colors.border }]}><View><Text style={{ color: colors.muted, fontFamily: "Manrope_600SemiBold", fontSize: 12 }}>Order total</Text><Text style={{ color: colors.text, fontFamily: "Fraunces_700Bold", fontSize: 28 }}>₹{order.total_amount.toLocaleString("en-IN")}</Text></View>{order.tracking_number && <View><Text style={{ color: colors.muted, fontFamily: "Manrope_600SemiBold", fontSize: 12 }}>Tracking</Text><Text style={{ color: colors.primary, fontFamily: "Manrope_700Bold" }}>{order.tracking_number}</Text></View>}</View>{!!error && <Text style={{ color: colors.danger, fontFamily: "Manrope_600SemiBold", lineHeight: 20, marginTop: 12 }}>{error}</Text>}{payment && isCustomer && <View style={[styles.payment, { backgroundColor: colors.primarySoft }]}><CreditCard color={colors.primary} size={25} /><View style={{ flex: 1 }}><Text style={{ color: colors.primary, fontFamily: "Manrope_700Bold", marginBottom: 3 }}>Secure payment required</Text><Text style={{ color: colors.text, fontFamily: "Manrope_400Regular", fontSize: 12 }}>Razorpay opens securely and the backend verifies capture before work proceeds.</Text></View><View style={{ minWidth: 125 }}><AppButton disabled={paying} onPress={() => void pay()}>{paying ? "Opening…" : payment.label}</AppButton></View></View>}
    {combinedInvoice && <InvoiceCard colors={colors} invoice={combinedInvoice} />}{isVendor && combinedInvoice?.status === "approved" && combinedInvoice.cloth_source === "vendor_supplied" && combinedInvoice.cloth_cost > 0 && combinedInvoice.payment_status === "pending" && <View style={{ marginTop: 9 }}><AppButton disabled={Boolean(busy)} onPress={() => void attachClothBill()} variant="secondary">{combinedInvoice.cloth_bill_url ? "Replace cloth bill" : "Attach cloth bill"}</AppButton></View>}{canEditCombined && <View style={{ marginTop: 12 }}><AppButton onPress={() => setInvoiceTarget("combined")}><FilePenLine color={colors.white} size={17} />{combinedInvoice ? "Edit combined invoice" : "Create combined invoice"}</AppButton></View>}{isCustomer && combinedInvoice?.status === "issued" && <InvoiceDecision note={decisionNote} onNote={setDecisionNote} onApprove={() => void decide(undefined)} onChange={() => void decide(undefined, "change_requested")} />}
    <Text style={{ color: colors.text, fontFamily: "Fraunces_700Bold", fontSize: 24, marginBottom: 12, marginTop: 22 }}>Tailoring items</Text>{order.order_items.map((item) => <View key={item.id} style={{ marginBottom: 14 }}><View style={[styles.item, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.itemIcon, { backgroundColor: colors.primarySoft }]}><Scissors color={colors.primary} size={22} /></View><View style={{ flex: 1 }}><Text style={{ color: colors.text, fontFamily: "Manrope_700Bold" }}>{item.design.title}</Text><Text style={{ color: colors.muted, fontFamily: "Manrope_400Regular", fontSize: 12 }}>{item.design.vendor_name} · ₹{item.price.toLocaleString("en-IN")}</Text></View><Pill tone={item.work_status === "completed" ? "success" : "primary"}>{workLabels[item.work_status] || item.work_status.replaceAll("_", " ")}</Pill></View>{!order.combined_order && item.invoice && <InvoiceCard colors={colors} invoice={item.invoice} />}{isVendor && !order.combined_order && item.invoice?.status === "approved" && item.invoice.cloth_source === "vendor_supplied" && item.invoice.cloth_cost > 0 && item.invoice.payment_status === "pending" && <View style={{ marginTop: 9 }}><AppButton disabled={Boolean(busy)} onPress={() => void attachClothBill(item)} variant="secondary">{item.invoice.cloth_bill_url ? "Replace cloth bill" : "Attach cloth bill"}</AppButton></View>}{isVendor && !order.combined_order && (!item.invoice || ["draft", "change_requested"].includes(item.invoice.status)) && <View style={{ marginTop: 9 }}><AppButton onPress={() => setInvoiceTarget(item)} variant="secondary"><FilePenLine color={colors.text} size={17} />{item.invoice ? "Edit invoice" : "Create invoice"}</AppButton></View>}{isCustomer && !order.combined_order && item.invoice?.status === "issued" && <InvoiceDecision note={decisionNote} onNote={setDecisionNote} onApprove={() => void decide(item)} onChange={() => void decide(item, "change_requested")} />}{isVendor && item.invoice?.status === "approved" && item.work_status === "awaiting_cloth" && <View style={{ marginTop: 9 }}><AppButton disabled={Boolean(busy)} onPress={() => void action(order.combined_order ? `/api/orders/vendor/${order.id}/cloth-received` : `/api/orders/vendor/items/${item.id}/cloth-received`)} variant="secondary"><PackageCheck color={colors.text} size={17} />Confirm customer cloth received</AppButton></View>}{isVendor && nextWorkLabel[item.work_status] && <View style={{ marginTop: 9 }}><AppButton disabled={Boolean(busy)} onPress={() => void vendorProgress(item)}>{nextWorkLabel[item.work_status]}</AppButton></View>}<OrderChat item={item} /></View>)}
    {isVendor && order.combined_order && allComplete && order.invoice?.final_payment_status === "paid" && !["ready_for_shipping", "shipped", "delivered"].includes(order.status) && <View style={{ marginBottom: 16 }}><AppButton disabled={Boolean(busy)} onPress={() => void action(`/api/orders/vendor/${order.id}/ship`)}><PackageCheck color={colors.white} size={17} />Ready for shipping</AppButton></View>}<View style={[styles.timeline, { backgroundColor: colors.surface, borderColor: colors.border }]}>{workflowStages.map((stage) => <View key={stage.key} style={styles.stage}>{stage.state === "complete" ? <CircleCheckBig color={colors.success} size={20} /> : stage.state === "current" ? <View style={[styles.currentStageIcon, { backgroundColor: colors.primarySoft }]}>{stage.key === "invoice" ? <FilePenLine color={colors.primary} size={17} /> : stage.key === "tailoring" ? <Scissors color={colors.primary} size={17} /> : stage.key === "payment" ? <CreditCard color={colors.primary} size={17} /> : <PackageCheck color={colors.primary} size={17} />}</View> : <View style={[styles.dot, { borderColor: colors.border }]} />}<Text style={[styles.stageLabel, { color: stage.state === "current" ? colors.primary : colors.text }]}>{stage.label}</Text><Text numberOfLines={2} style={[styles.stageDetail, { color: stage.state === "current" ? colors.primary : colors.muted }]}>{stage.detail}</Text></View>)}</View>{invoiceTarget && <OrderInvoiceEditor item={invoiceTarget === "combined" ? undefined : invoiceTarget} onClose={() => setInvoiceTarget(null)} onUpdated={setOrder} order={order} />}</Screen>
}

const InvoiceDecision = ({ note, onNote, onApprove, onChange }: { note: string; onNote: (value: string) => void; onApprove: () => void; onChange: () => void }) => <View style={styles.decision}><Field label="Note to vendor (required only for changes)" maxLength={1000} multiline numberOfLines={3} onChangeText={onNote} style={{ minHeight: 80, textAlignVertical: "top" }} value={note} /><View style={styles.decisionActions}><View style={{ flex: 1 }}><AppButton onPress={onChange} variant="secondary">Request changes</AppButton></View><View style={{ flex: 1 }}><AppButton onPress={onApprove}>Approve invoice</AppButton></View></View></View>

const styles = StyleSheet.create({ summary: { alignItems: "center", borderRadius: 18, borderWidth: 1, flexDirection: "row", justifyContent: "space-between", padding: 16 }, payment: { alignItems: "center", borderRadius: 18, flexDirection: "row", flexWrap: "wrap", gap: 11, marginTop: 16, padding: 14 }, item: { alignItems: "center", borderRadius: 16, borderWidth: 1, flexDirection: "row", gap: 11, padding: 13 }, itemIcon: { alignItems: "center", borderRadius: 13, height: 44, justifyContent: "center", width: 44 }, invoice: { borderRadius: 17, borderWidth: 1, marginTop: 10, padding: 14 }, invoiceHeader: { alignItems: "flex-start", flexDirection: "row", justifyContent: "space-between", marginBottom: 9 }, invoiceTotals: { alignItems: "flex-end", borderTopColor: "rgba(128,128,128,.22)", borderTopWidth: 1, marginTop: 11, paddingTop: 11 }, decision: { borderRadius: 17, marginTop: 10, paddingTop: 3 }, decisionActions: { flexDirection: "row", gap: 9 }, chat: { borderRadius: 18, borderWidth: 1, marginTop: 10, padding: 13 }, chatHeading: { alignItems: "center", flexDirection: "row", gap: 9, marginBottom: 12 }, messages: { gap: 8, marginBottom: 10 }, message: { borderRadius: 14, borderWidth: 1, maxWidth: "88%", minWidth: "48%", padding: 10 }, composer: { alignItems: "flex-end", flexDirection: "row", gap: 8 }, chatInput: { borderRadius: 14, borderWidth: 1, flex: 1, fontFamily: "Manrope_500Medium", maxHeight: 100, minHeight: 48, paddingHorizontal: 13, paddingVertical: 12 }, sendButton: { alignItems: "center", borderRadius: 14, height: 48, justifyContent: "center", width: 48 }, timeline: { borderRadius: 18, borderWidth: 1, flexDirection: "row", justifyContent: "space-between", marginTop: 8, paddingHorizontal: 8, paddingVertical: 13 }, stage: { alignItems: "center", flex: 1, gap: 3, minWidth: 0, paddingHorizontal: 2 }, currentStageIcon: { alignItems: "center", borderRadius: 11, height: 22, justifyContent: "center", width: 22 }, stageLabel: { fontFamily: "Manrope_700Bold", fontSize: 11, marginTop: 3, textAlign: "center" }, stageDetail: { fontFamily: "Manrope_500Medium", fontSize: 9, lineHeight: 12, minHeight: 24, textAlign: "center" }, dot: { borderRadius: 10, borderWidth: 2, height: 20, width: 20 } })
