import { useCallback, useEffect, useMemo, useState } from "react"
import { Alert, StyleSheet, Text, View } from "react-native"
import { useLocalSearchParams } from "expo-router"
import { CircleCheckBig, CreditCard, PackageCheck, Scissors } from "lucide-react-native"
import { api } from "@/lib/api"
import type { InvoiceSummary, Order } from "@/types/api"
import { openRazorpayCheckout, type PaymentScope } from "@/payments/razorpay"
import { AppButton, ErrorState, LoadingState, PageHeader, Pill, Screen } from "@/components/ui"
import { useTheme } from "@/theme/theme"

export default function OrderDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { colors } = useTheme(); const [order, setOrder] = useState<Order | null>(null); const [loading, setLoading] = useState(true); const [paying, setPaying] = useState(false); const [error, setError] = useState("")
  const load = useCallback(async () => { setError(""); try { setOrder(await api<Order>(`/api/orders/${id}`)) } catch (value) { setError((value as Error).message) } finally { setLoading(false) } }, [id])
  useEffect(() => { void load() }, [load])
  const payment = useMemo(() => {
    if (!order) return null
    const combined = order.combined_order && order.invoice ? { invoice: order.invoice, resourceId: order.id, prefix: "combined_order" as const } : order.order_items.length === 1 && order.order_items[0].invoice ? { invoice: order.order_items[0].invoice, resourceId: order.order_items[0].id, prefix: "order_item" as const } : null
    if (!combined || combined.invoice.status !== "approved") return null
    if (combined.invoice.payment_status === "pending" && combined.invoice.cloth_cost > 0) return { label: `Pay cloth cost · ₹${combined.invoice.cloth_cost.toLocaleString("en-IN")}`, scope: combined.prefix as PaymentScope, resourceId: combined.resourceId }
    const complete = order.order_items.every((item) => item.work_status === "completed")
    if (complete && combined.invoice.final_payment_status === "pending") return { label: "Pay final order balance", scope: `${combined.prefix}_final` as PaymentScope, resourceId: combined.resourceId }
    return null
  }, [order])
  const pay = async () => { if (!payment) return; setPaying(true); try { const result = await openRazorpayCheckout(payment.scope, payment.resourceId); Alert.alert("Payment verified", result.message); await load() } catch (value) { const failure = value as { description?: string; message?: string }; Alert.alert("Payment not completed", failure.description || failure.message || "You can safely try again.") } finally { setPaying(false) } }
  if (loading) return <Screen scroll={false}><LoadingState label="Opening order…" /></Screen>
  if (error || !order) return <Screen><PageHeader back title="Order" /><ErrorState message={error || "Order not found"} retry={() => void load()} /></Screen>
  return <Screen><PageHeader action={<Pill tone={order.status === "delivered" ? "success" : "primary"}>{order.status.replaceAll("_", " ")}</Pill>} back subtitle={`Placed ${new Date(order.created_at).toLocaleString("en-IN")}`} title={`Order #${order.id}`} /><View style={[styles.summary, { backgroundColor: colors.surface, borderColor: colors.border }]}><View><Text style={{ color: colors.muted, fontFamily: "Manrope_600SemiBold", fontSize: 12 }}>Order total</Text><Text style={{ color: colors.text, fontFamily: "Fraunces_700Bold", fontSize: 28 }}>₹{order.total_amount.toLocaleString("en-IN")}</Text></View>{order.tracking_number && <View><Text style={{ color: colors.muted, fontFamily: "Manrope_600SemiBold", fontSize: 12 }}>Tracking</Text><Text style={{ color: colors.primary, fontFamily: "Manrope_700Bold" }}>{order.tracking_number}</Text></View>}</View>{payment && <View style={[styles.payment, { backgroundColor: colors.primarySoft }]}><CreditCard color={colors.primary} size={25} /><View style={{ flex: 1 }}><Text style={{ color: colors.primary, fontFamily: "Manrope_700Bold", marginBottom: 3 }}>Secure payment required</Text><Text style={{ color: colors.text, fontFamily: "Manrope_400Regular", fontSize: 12 }}>Razorpay opens securely and the backend verifies capture before work proceeds.</Text></View><View style={{ minWidth: 125 }}><AppButton disabled={paying} onPress={() => void pay()}>{paying ? "Opening…" : payment.label}</AppButton></View></View>}<Text style={{ color: colors.text, fontFamily: "Fraunces_700Bold", fontSize: 24, marginBottom: 12, marginTop: 22 }}>Tailoring items</Text>{order.order_items.map((item) => <View key={item.id} style={[styles.item, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.itemIcon, { backgroundColor: colors.primarySoft }]}><Scissors color={colors.primary} size={22} /></View><View style={{ flex: 1 }}><Text style={{ color: colors.text, fontFamily: "Manrope_700Bold" }}>{item.design.title}</Text><Text style={{ color: colors.muted, fontFamily: "Manrope_400Regular", fontSize: 12 }}>{item.design.vendor_name}</Text></View><Pill tone={item.work_status === "completed" ? "success" : "primary"}>{item.work_status.replaceAll("_", " ")}</Pill></View>)}<View style={[styles.timeline, { borderColor: colors.border }]}>{["Invoice approved", "Tailoring", "Payment", order.status === "delivered" ? "Delivered" : "Fulfilment"].map((label, index) => <View key={label} style={styles.stage}>{index < 1 || order.status === "delivered" ? <CircleCheckBig color={colors.success} size={19} /> : index === 3 ? <PackageCheck color={colors.primary} size={19} /> : <View style={[styles.dot, { borderColor: colors.border }]} />}<Text style={{ color: colors.muted, fontFamily: "Manrope_600SemiBold", fontSize: 11 }}>{label}</Text></View>)}</View></Screen>
}

const styles = StyleSheet.create({ summary: { alignItems: "center", borderRadius: 18, borderWidth: 1, flexDirection: "row", justifyContent: "space-between", padding: 16 }, payment: { alignItems: "center", borderRadius: 18, flexDirection: "row", gap: 11, marginTop: 16, padding: 14 }, item: { alignItems: "center", borderRadius: 16, borderWidth: 1, flexDirection: "row", gap: 11, marginBottom: 9, padding: 13 }, itemIcon: { alignItems: "center", borderRadius: 13, height: 44, justifyContent: "center", width: 44 }, timeline: { borderRadius: 18, borderWidth: 1, flexDirection: "row", justifyContent: "space-between", marginTop: 22, padding: 14 }, stage: { alignItems: "center", flex: 1, gap: 7 }, dot: { borderRadius: 10, borderWidth: 2, height: 19, width: 19 } })
